// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgliebjbeytyynpefjzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbGllYmpiZXl0eXlucGVmanp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDM2NzIsImV4cCI6MjA3MDA3OTY3Mn0.okGKGkeUYlF1z1EbqSEdNap4FomRyDhYjkuOi2WvrBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});